---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fxa-graphql-api
  description: GraphQL API for Mozilla Accounts
  annotations:
    sentry.io/project-slug: mozilla/fxa-graphql-api
    circleci.com/project-slug: github/mozilla/fxa
  tags:
    - typescript
    - node
    - nestjs
    - graphql
spec:
  type: service
  lifecycle: production
  owner: fxa-team
  system: mozilla-accounts
  providesApis:
    - fxa-graphql-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: fxa-graphql-api
  description: Mozilla Accounts GraphQL API
spec:
  type: graphql
  lifecycle: production
  owner: fxa-team
  system: mozilla-accounts
  definition:
    $text: ./src/schema.gql
