name: Tag Release
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'What train is this?  eg. 275'
        required: true
permissions: {}
jobs:
  tagrelease:
    permissions:
      contents: write # To create a branch and tags
    runs-on: ubuntu-latest

    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        shell: bash
      - name: Check out code
        uses: actions/checkout@v3
      - name: Create release branch
        run: git checkout -b train-${{ github.event.inputs.versionName }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "${{ github.triggering_actor }}"
          git config user.email "noreply@github.com"

      - name: Commit update to branch
        run: |
          git push origin train-${{ github.event.inputs.versionName }}

      - name: Make a new tag
        run: |
          git tag -a "v1.${{ github.event.inputs.versionName }}.0" -m "Train release ${{ github.event.inputs.versionName }}"
          git push origin v1.${{ github.event.inputs.versionName }}.0
